version: 2
jobs:
  do_everything:
    docker:
      - image: mishguru/circleci:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: "Set Up Env Vars"
          command: |
            echo $NPMRC > ~/.npmrc
            mkdir ~/npm
            echo prefix = ~/npm >> ~/.npmrc
            echo 'export PATH=$PATH:~/npm/bin/' >> $BASH_ENV
            echo 'export DOCKER_BASE="mishguru/fanoutbase:latest"' >> $BASH_ENV
            echo 'export RANCHER_INTERNAL_NAMESPACE="aux"' >> $BASH_ENV
      - run:
          name: "Install the @mishguru/service package"
          command: |
            npm install -g @mishguru/service@4
      - run:
          name: "Start the mysql database"
          command: |
            service-start-database
      - run:
          name: "Install dependencies"
          command: |
            service-install-dependencies
      - run:
          name: Test
          command: |
            service-run-tests
      - run:
          name: Deploy
          command: |
            service-push-docker-tag
            service-deploy-to-rancher

workflows:
  version: 2
  build:
    jobs:
      - do_everything:
          context: shared
          filters:
            tags:
              only: /.*/
